site_name: 【布客】PyTorch 中文翻译
site_url: https://pytorch.apachecn.org

# Repository
repo_name: apachecn/pytorch-doc-zh
repo_url: https://github.com/apachecn/pytorch-doc-zh

theme:
  name: material
  custom_dir: themes_material
  logo: https://data.apachecn.org/img/logo/logo_green.png
  locale: zh_CN
  analytics:
    gtag: G-8DP4GX97XY
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - attr_list
  - md_in_html

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "PyTorch 中文文档 & 教程": "index.md"
  - "PyTorch 新特性":
    - "V2.3":  "LatestChanges/PyTorch_V2.3.md"
    - "V2.2":  "LatestChanges/PyTorch_V2.2.md"
    - "V2.1":  "LatestChanges/PyTorch_V2.1.md"
    - "V2.0":  "LatestChanges/PyTorch_V2.0.md"
    - "V1.13": "LatestChanges/PyTorch_V1.13.md"
    - "V1.12": "LatestChanges/PyTorch_V1.12.md"
    - "V1.11": "LatestChanges/PyTorch_V1.11.md"
    - "V1.10": "LatestChanges/PyTorch_V1.10.md"
    - "V1.9":  "LatestChanges/PyTorch_V1.9.md"
    - "V1.8":  "LatestChanges/PyTorch_V1.8.md"
    - "V1.7":  "LatestChanges/PyTorch_V1.7.md"
    - "V1.6":  "LatestChanges/PyTorch_V1.6.md"
    - "V1.5":  "LatestChanges/PyTorch_V1.5.md"
    - "V1.4":  "LatestChanges/PyTorch_V1.4.md"
    - "V1.3":  "LatestChanges/PyTorch_V1.3.md"
    - "V1.2":  "LatestChanges/PyTorch_V1.2.md"
  - "PyTorch 2.x 中文文档 & 教程":
    - "中文教程":
      - "PyTorch Recipes":
        - "See All Recipes": "2.0/tutorials/recipes/recipes_index.md"
        - "See All Prototype Recipes": "2.0/tutorials/prototype/prototype_index.md"
      - "Introduction to PyTorch":
        - "Learn the Basics": "2.0/tutorials/beginner/basics/intro.md"
        - "Quickstart": "2.0/tutorials/beginner/basics/quickstart_tutorial.md"
        - "Tensors": "2.0/tutorials/beginner/basics/tensorqs_tutorial.md"
        - "Datasets & DataLoaders": "2.0/tutorials/beginner/basics/data_tutorial.md"
        - "Transforms": "2.0/tutorials/beginner/basics/transforms_tutorial.md"
        - "Build the Neural Network": "2.0/tutorials/beginner/basics/buildmodel_tutorial.md"
        - "Automatic Differentiation with torch.autograd": "2.0/tutorials/beginner/basics/autogradqs_tutorial.md"
        - "Optimizing Model Parameters": "2.0/tutorials/beginner/basics/optimization_tutorial.md"
        - "Save and Load the Model": "2.0/tutorials/beginner/basics/saveloadrun_tutorial.md"
      - "Introduction to PyTorch on YouTube":
        - "Introduction to PyTorch - YouTube Series": "2.0/tutorials/beginner/introyt.md"
        - "Introduction to PyTorch": "2.0/tutorials/beginner/introyt/introyt1_tutorial.md"
        - "Introduction to PyTorch Tensors": "2.0/tutorials/beginner/introyt/tensors_deeper_tutorial.md"
        - "The Fundamentals of Autograd": "2.0/tutorials/beginner/introyt/autogradyt_tutorial.md"
        - "Building Models with PyTorch": "2.0/tutorials/beginner/introyt/modelsyt_tutorial.md"
        - "PyTorch TensorBoard Support": "2.0/tutorials/beginner/introyt/tensorboardyt_tutorial.md"
        - "Training with PyTorch": "2.0/tutorials/beginner/introyt/trainingyt.md"
        - "Model Understanding with Captum": "2.0/tutorials/beginner/introyt/captumyt.md"
      - "Learning PyTorch":
        - "Deep Learning with PyTorch: A 60 Minute Blitz": "2.0/tutorials/beginner/deep_learning_60min_blitz.md"
        - "Learning PyTorch with Examples": "2.0/tutorials/beginner/pytorch_with_examples.md"
        - "What is torch.nn really?": "2.0/tutorials/beginner/nn_tutorial.md"
        - "Visualizing Models, Data, and Training with TensorBoard": "2.0/tutorials/intermediate/tensorboard_tutorial.md"
      - "Image and Video":
        - "TorchVision Object Detection Finetuning Tutorial": "2.0/tutorials/intermediate/torchvision_tutorial.md"
        - "Transfer Learning for Computer Vision Tutorial": "2.0/tutorials/beginner/transfer_learning_tutorial.md"
        - "Adversarial Example Generation": "2.0/tutorials/beginner/fgsm_tutorial.md"
        - "DCGAN Tutorial": "2.0/tutorials/beginner/dcgan_faces_tutorial.md"
        - "Spatial Transformer Networks Tutorial": "2.0/tutorials/intermediate/spatial_transformer_tutorial.md"
        - "Optimizing Vision Transformer Model for Deployment": "2.0/tutorials/beginner/vt_tutorial.md"
      - "Audio":
        - "Audio I/O": "2.0/tutorials/beginner/audio_io_tutorial.md"
        - "Audio Resampling": "2.0/tutorials/beginner/audio_resampling_tutorial.md"
        - "Audio Data Augmentation": "2.0/tutorials/beginner/audio_data_augmentation_tutorial.md"
        - "Audio Feature Extractions": "2.0/tutorials/beginner/audio_feature_extractions_tutorial.md"
        - "Audio Feature Augmentation": "2.0/tutorials/beginner/audio_feature_augmentation_tutorial.md"
        - "Audio Datasets": "2.0/tutorials/beginner/audio_datasets_tutorial.md"
        - "Speech Recognition with Wav2Vec2": "2.0/tutorials/intermediate/speech_recognition_pipeline_tutorial.md"
        - "Text-to-speech with Tacotron2": "2.0/tutorials/intermediate/text_to_speech_with_torchaudio.md"
        - "Forced Alignment with Wav2Vec2": "2.0/tutorials/intermediate/forced_alignment_with_torchaudio_tutorial.md"
      - "Text":
        - "Language Modeling with nn.Transformer and torchtext": "2.0/tutorials/beginner/transformer_tutorial.md"
        - "Fast Transformer Inference with Better Transformer": "2.0/tutorials/beginner/bettertransformer_tutorial.md"
        - "NLP From Scratch: Classifying Names with a Character-Level RNN": "2.0/tutorials/intermediate/char_rnn_classification_tutorial.md"
        - "NLP From Scratch: Generating Names with a Character-Level RNN": "2.0/tutorials/intermediate/char_rnn_generation_tutorial.md"
        - "NLP From Scratch: Translation with a Sequence to Sequence Network and Attention": "2.0/tutorials/intermediate/seq2seq_translation_tutorial.md"
        - "Text classification with the torchtext library": "2.0/tutorials/beginner/text_sentiment_ngrams_tutorial.md"
        - "Language Translation with nn.Transformer and torchtext": "2.0/tutorials/beginner/translation_transformer.md"
        - "Preprocess custom text dataset using Torchtext": "2.0/tutorials/beginner/torchtext_custom_dataset_tutorial.md"
      - "Backends":
        - "Introduction to ONNX": "2.0/tutorials/beginner/onnx/intro_onnx.md"
      - "Reinforcement Learning":
        - "Reinforcement Learning (DQN) Tutorial": "2.0/tutorials/intermediate/reinforcement_q_learning.md"
        - "Reinforcement Learning (PPO) with TorchRL Tutorial": "2.0/tutorials/intermediate/reinforcement_ppo.md"
        - "Train a Mario-playing RL Agent": "2.0/tutorials/intermediate/mario_rl_tutorial.md"
      - "Deploying PyTorch Models in Production":
        - "Introduction to ONNX": "2.0/tutorials/beginner/onnx/intro_onnx.md"
        - "Deploying PyTorch in Python via a REST API with Flask": "2.0/tutorials/intermediate/flask_rest_api_tutorial.md"
        - "Introduction to TorchScript": "2.0/tutorials/beginner/Intro_to_TorchScript_tutorial.md"
        - "Loading a TorchScript Model in C++": "2.0/tutorials/advanced/cpp_export.md"
        - "(optional) Exporting a Model from PyTorch to ONNX and Running it using ONNX Runtime": "2.0/tutorials/advanced/super_resolution_with_onnxruntime.md"
        - "Real Time Inference on Raspberry Pi 4 (30 fps!)": "2.0/tutorials/intermediate/realtime_rpi.md"
      - "Code Transforms with FX":
        - "(beta) Building a Convolution/Batch Norm fuser in FX": "2.0/tutorials/intermediate/fx_conv_bn_fuser.md"
        - "(beta) Building a Simple CPU Performance Profiler with FX": "2.0/tutorials/intermediate/fx_profiling_tutorial.md"
      - "Frontend APIs":
        - "(beta) Channels Last Memory Format in PyTorch": "2.0/tutorials/intermediate/memory_format_tutorial.md"
        - "Forward-mode Automatic Differentiation (Beta)": "2.0/tutorials/intermediate/forward_ad_usage.md"
        - "Jacobians, Hessians, hvp, vhp, and more: composing function transforms": "2.0/tutorials/intermediate/jacobians_hessians.md"
        - "Model ensembling": "2.0/tutorials/intermediate/ensembling.md"
        - "Per-sample-gradients": "2.0/tutorials/intermediate/per_sample_grads.md"
        - "Using the PyTorch C++ Frontend": "2.0/tutorials/advanced/cpp_frontend.md"
        - "Dynamic Parallelism in TorchScript": "2.0/tutorials/advanced/torch-script-parallelism.md"
        - "Autograd in C++ Frontend": "2.0/tutorials/advanced/cpp_autograd.md"
      - "Extending PyTorch":
        - "Double Backward with Custom Functions": "2.0/tutorials/intermediate/custom_function_double_backward_tutorial.md"
        - "Fusing Convolution and Batch Norm using Custom Function": "2.0/tutorials/intermediate/custom_function_conv_bn_tutorial.md"
        - "Custom C++ and CUDA Extensions": "2.0/tutorials/advanced/cpp_extension.md"
        - "Extending TorchScript with Custom C++ Operators": "2.0/tutorials/advanced/torch_script_custom_ops.md"
        - "Extending TorchScript with Custom C++ Classes": "2.0/tutorials/advanced/torch_script_custom_classes.md"
        - "Registering a Dispatched Operator in C++": "2.0/tutorials/advanced/dispatcher.md"
        - "Extending dispatcher for a new backend in C++": "2.0/tutorials/advanced/extend_dispatcher.md"
        - "Facilitating New Backend Integration by PrivateUse1": "2.0/tutorials/advanced/privateuseone.md"
      - "Model Optimization":
        - "Profiling your PyTorch Module": "2.0/tutorials/beginner/profiler.md"
        - "PyTorch Profiler With TensorBoard": "2.0/tutorials/intermediate/tensorboard_profiler_tutorial.md"
        - "Hyperparameter tuning with Ray Tune": "2.0/tutorials/beginner/hyperparameter_tuning_tutorial.md"
        - "Optimizing Vision Transformer Model for Deployment": "2.0/tutorials/beginner/vt_tutorial.md"
        - "Parametrizations Tutorial": "2.0/tutorials/intermediate/parametrizations.md"
        - "Pruning Tutorial": "2.0/tutorials/intermediate/pruning_tutorial.md"
        - "(beta) Dynamic Quantization on an LSTM Word Language Model": "2.0/tutorials/advanced/dynamic_quantization_tutorial.md"
        - "(beta) Dynamic Quantization on BERT": "2.0/tutorials/intermediate/dynamic_quantization_bert_tutorial.md"
        - "(beta) Quantized Transfer Learning for Computer Vision Tutorial": "2.0/tutorials/intermediate/quantized_transfer_learning_tutorial.md"
        - "(beta) Static Quantization with Eager Mode in PyTorch": "2.0/tutorials/advanced/static_quantization_tutorial.md"
        - "Grokking PyTorch Intel CPU performance from first principles": "2.0/tutorials/intermediate/torchserve_with_ipex.md"
        - "Grokking PyTorch Intel CPU performance from first principles (Part 2)": "2.0/tutorials/intermediate/torchserve_with_ipex_2.md"
        - "Getting Started - Accelerate Your Scripts with nvFuser": "2.0/tutorials/intermediate/nvfuser_intro_tutorial.md"
        - "Multi-Objective NAS with Ax": "2.0/tutorials/intermediate/ax_multiobjective_nas_tutorial.md"
        - "torch.compile Tutorial": "2.0/tutorials/intermediate/torch_compile_tutorial.md"
        - "Inductor CPU backend debugging and profiling": "2.0/tutorials/intermediate/inductor_debug_cpu.md"
        - "(Beta) Implementing High-Performance Transformers with Scaled Dot Product Attention (SDPA)": "2.0/tutorials/intermediate/scaled_dot_product_attention_tutorial.md"
        - "Using SDPA with torch.compile": "2.0/tutorials/intermediate/scaled_dot_product_attention_tutorial#using-sdpa-with-torch-compile.md"
        - "Conclusion": "2.0/tutorials/intermediate/scaled_dot_product_attention_tutorial#conclusion.md"
        - "Knowledge Distillation Tutorial": "2.0/tutorials/beginner/knowledge_distillation_tutorial.md"
      - "Parallel and Distributed Training":
        - "Distributed and Parallel Training Tutorials": "2.0/tutorials/distributed/home.md"
        - "PyTorch Distributed Overview": "2.0/tutorials/beginner/dist_overview.md"
        - "Distributed Data Parallel in PyTorch - Video Tutorials": "2.0/tutorials/beginner/ddp_series_intro.md"
        - "Single-Machine Model Parallel Best Practices": "2.0/tutorials/intermediate/model_parallel_tutorial.md"
        - "Getting Started with Distributed Data Parallel": "2.0/tutorials/intermediate/ddp_tutorial.md"
        - "Writing Distributed Applications with PyTorch": "2.0/tutorials/intermediate/dist_tuto.md"
        - "Getting Started with Fully Sharded Data Parallel(FSDP)": "2.0/tutorials/intermediate/FSDP_tutorial.md"
        - "Advanced Model Training with Fully Sharded Data Parallel (FSDP)": "2.0/tutorials/intermediate/FSDP_adavnced_tutorial.md"
        - "Customize Process Group Backends Using Cpp Extensions": "2.0/tutorials/intermediate/process_group_cpp_extension_tutorial.md"
        - "Getting Started with Distributed RPC Framework": "2.0/tutorials/intermediate/rpc_tutorial.md"
        - "Implementing a Parameter Server Using Distributed RPC Framework": "2.0/tutorials/intermediate/rpc_param_server_tutorial.md"
        - "Distributed Pipeline Parallelism Using RPC": "2.0/tutorials/intermediate/dist_pipeline_parallel_tutorial.md"
        - "Implementing Batch RPC Processing Using Asynchronous Executions": "2.0/tutorials/intermediate/rpc_async_execution.md"
        - "Combining Distributed DataParallel with Distributed RPC Framework": "2.0/tutorials/advanced/rpc_ddp_tutorial.md"
        - "Training Transformer models using Pipeline Parallelism": "2.0/tutorials/intermediate/pipeline_tutorial.md"
        - "Training Transformer models using Distributed Data Parallel and Pipeline Parallelism": "2.0/tutorials/advanced/ddp_pipeline.md"
        - "Distributed Training with Uneven Inputs Using the Join Context Manager": "2.0/tutorials/advanced/generic_join.md"
      - "Mobile":
        - "Image Segmentation DeepLabV3 on iOS": "2.0/tutorials/beginner/deeplabv3_on_ios.md"
        - "Image Segmentation DeepLabV3 on Android": "2.0/tutorials/beginner/deeplabv3_on_android.md"
      - "Recommendation Systems":
        - "Introduction to TorchRec": "2.0/tutorials/intermediate/torchrec_tutorial.md"
        - "Exploring TorchRec sharding": "2.0/tutorials/advanced/sharding.md"
      - "Multimodality":
        - "TorchMultimodal Tutorial: Finetuning FLAVA": "2.0/tutorials/beginner/flava_finetuning_tutorial.md"
    - "中文文档":
      - "介绍" : "2.0/docs/README.md"
      - "Pytorch"     : "https://pytorch.org/docs/stable/index.html"
      - "Torchaudio"  : "https://pytorch.org/audio/stable/index.html"
      - "TorchText"   : "https://pytorch.org/text/stable/index.html"
      - "TorchVision" : "https://pytorch.org/vision/stable/index.html"
      - "TorchArrow"  : "https://pytorch.org/torcharrow/beta/index.html"
      - "TorchRec"    : "https://pytorch.org/torchrec/"
      - "TorchServe"  : "https://pytorch.org/serve/"
      - "TorchX"      : "https://pytorch.org/torchx/latest/"
      - "PyTorch on XLA Devices": "https://pytorch.org/xla/release/2.3/index.html"
  - "PyTorch 1.7 中文文档": "https://pytorch1x.apachecn.org"
  - "PyTorch 1.4 中文文档 & 教程": "https://pytorch1x.apachecn.org"
  - "PyTorch 1.0 中文文档 & 教程": "https://pytorch1x.apachecn.org"
  - "PyTorch 0.4 中文文档": "https://pytorch0x.apachecn.org"
  - "PyTorch 0.3 中文文档 & 教程": "https://pytorch0x.apachecn.org"
  - "PyTorch 0.2 中文文档": "https://pytorch0x.apachecn.org"
  - "贡献指南": "contrib.md"
  - "关于我们": "https://www.apachecn.org/about"
  - "加入我们": "https://www.apachecn.org/join"
  - "中文资源合集": "https://docs.apachecn.org"
