site_name: 【布客】PyTorch 中文翻译
site_url: https://pytorch.apachecn.org

# Repository
repo_name: apachecn/pytorch-doc-zh
repo_url: https://github.com/apachecn/pytorch-doc-zh

theme:
  name: material
  custom_dir: themes_material
  locale: zh_CN
  analytics:
    gtag: G-8DP4GX97XY
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "PyTorch 中文文档 & 教程": "index.md"
  - "PyTorch 新特性":
    - "V2.0":  "LatestChanges/PyTorch_V2.0.md"
    - "V1.13": "LatestChanges/PyTorch_V1.13.md"
    - "V1.12": "LatestChanges/PyTorch_V1.12.md"
    - "V1.11": "LatestChanges/PyTorch_V1.11.md"
    - "V1.10": "LatestChanges/PyTorch_V1.10.md"
    - "V1.9":  "LatestChanges/PyTorch_V1.9.md"
    - "V1.8":  "LatestChanges/PyTorch_V1.8.md"
    - "V1.7":  "LatestChanges/PyTorch_V1.7.md"
    - "V1.6":  "LatestChanges/PyTorch_V1.6.md"
    - "V1.5":  "LatestChanges/PyTorch_V1.5.md"
    - "V1.4":  "LatestChanges/PyTorch_V1.4.md"
    - "V1.3":  "LatestChanges/PyTorch_V1.3.md"
    - "V1.2":  "LatestChanges/PyTorch_V1.2.md"
  - "PyTorch 2.0 中文文档 & 教程":
    - "中文教程":
      - "PyTorch简介":
        - "学习基本知识":                   "2.0/tutorials/beginner/basics/intro.md"
        - "快速入门":                      "2.0/tutorials/beginner/basics/quickstart_tutorial.md"
        - "Tensors介绍":                  "2.0/tutorials/beginner/basics/tensors_tutorial.md"
        - "数据集和数据加载器":             "2.0/tutorials/beginner/basics/data_tutorial.md"
        - "Transforms介绍":               "2.0/tutorials/beginner/basics/transforms_tutorial.md"
        - "构建神经网络模型":               "2.0/tutorials/beginner/basics/buildmodel_tutorial.md"
        - "自动微分运算 - Torch.AutoGrad": "2.0/tutorials/beginner/basics/autogradqs_tutorial.md"
        - "优化模型参数":                  "2.0/tutorials/beginner/basics/optimization_tutorial.md"
        - "模型保存和加载":                 "2.0/tutorials/beginner/basics/saveloadrun_tutorial.md"
      - "用YouTube入门PyTorch":
        - "PyTorch 入门 - YouTube系列":  "2.0/tutorials/beginner/introyt.md"
        - "PyTorch 入门":               "2.0/tutorials/beginner/introyt/introyt1_tutorial.md"
        - "PyTorch 张量入门":            "2.0/tutorials/beginner/introyt/tensors_deeper_tutorial.md"
        - "自动微分的基础知识":            "2.0/tutorials/beginner/introyt/autogradyt_tutorial.md"
        - "使用 PyTorch 构建模型":         "2.0/tutorials/beginner/introyt/modelsyt_tutorial.md"
        - "PyTorch 的 TensorBoard 支持":  "2.0/tutorials/beginner/introyt/tensorboardyt_tutorial.md"
        - "使用 PyTorch 训练":            "2.0/tutorials/beginner/introyt/trainingyt.md"
        - "使用 Captum 进行模型理解":      "2.0/tutorials/beginner/introyt/captumyt.md"
      - "学习PyTorch":
        - "通过示例学习PyTorch":        "2.0/tutorials/beginner/pytorch_with_examples.md"
        - "究竟什么是 TORCH.NN":       "2.0/tutorials/beginner/nn_tutorial.md"
      - "强化学习":
        - "强化学习 （DQN）教程": "2.0/tutorials/intermediate/reinforcement_q_learning.md"
        - "训练玩马里奥的 RL 智能体": "2.0/tutorials/intermediate/TrainaMarioPlayingRLAgent.md"
      - "在生产中部署PyTorch模型":
        - "通过带有Flask的REST API在Python中部署PyTorch": "2.0/tutorials/intermediate/flask_rest_api_tutorial.md"
        - "TorchScript 简介": "2.0/tutorials/beginner/Intro_to_TorchScript_tutorial.md"
        - "在C++中加载 TorchScript 模型": "2.0/tutorials/advanced/cpp_export.md"
    - "中文文档":
      - "介绍": "2.0/docs/README.md"
  - "PyTorch 1.7 中文文档":
    - "学习 PyTorch":
      - "PyTorch 深度学习：60 分钟的突击":
        - "介绍": "1.7/02.md"
        - "张量": "1.7/03.md"
        - "torch.autograd的简要介绍": "1.7/04.md"
        - "神经网络": "1.7/05.md"
        - "训练分类器": "1.7/06.md"
      - "通过示例学习 PyTorch":
        - "介绍": "1.7/07.md"
        - "热身：NumPy": "1.7/08.md"
        - "PyTorch：张量": "1.7/09.md"
        - "PyTorch：张量和 Autograd": "1.7/10.md"
        - "PyTorch：定义新的 Autograd 函数": "1.7/11.md"
        - "PyTorch：nn": "1.7/12.md"
        - "PyTorch：optim": "1.7/13.md"
        - "PyTorch：自定义nn模块": "1.7/14.md"
        - "PyTorch：控制流 - 权重共享": "1.7/15.md"
      - "torch.nn到底是什么？": "1.7/16.md"
      - "使用 TensorBoard 可视化模型，数据和训练": "1.7/17.md"
    - "图片/视频":
      - "torchvision对象检测微调教程": "1.7/19.md"
      - "计算机视觉的迁移学习教程": "1.7/20.md"
      - "对抗示例生成": "1.7/21.md"
      - "DCGAN 教程": "1.7/22.md"
    - "音频":
      - "音频 I/O 和torchaudio的预处理": "1.7/24.md"
      - "使用torchaudio的语音命令识别": "1.7/25.md"
    - "文本":
      - "使用nn.Transformer和torchtext的序列到序列建模": "1.7/27.md"
      - "从零开始的 NLP：使用字符级 RNN 分类名称": "1.7/28.md"
      - "从零开始的 NLP：使用字符级 RNN 生成名称": "1.7/29.md"
      - "从零开始的 NLP：使用序列到序列网络和注意力的翻译": "1.7/30.md"
      - "使用torchtext的文本分类": "1.7/31.md"
      - "torchtext语言翻译": "1.7/32.md"
    - "强化学习":
      - "强化学习（DQN）教程": "1.7/34.md"
      - "训练玩马里奥的 RL 智能体": "1.7/35.md"
    - "在生产中部署 PyTorch 模型":
      - "通过使用 Flask 的 REST API 在 Python 中部署 PyTorch": "1.7/37.md"
      - "TorchScript 简介": "1.7/38.md"
      - "在 C-- 中加载 TorchScript 模型": "1.7/39.md"
      - "将模型从 PyTorch 导出到 ONNX 并使用 ONNX 运行时运行它（可选）": "1.7/40.md"
    - "前端 API":
      - "PyTorch 中的命名张量简介（原型）": "1.7/42.md"
      - "PyTorch 中通道在最后的内存格式（beta）": "1.7/43.md"
      - "使用 PyTorch C-- 前端": "1.7/44.md"
      - "自定义 C-- 和 CUDA 扩展": "1.7/45.md"
      - "使用自定义 C-- 运算符扩展 TorchScript": "1.7/46.md"
      - "使用自定义 C-- 类扩展 TorchScript": "1.7/47.md"
      - "TorchScript 中的动态并行性": "1.7/48.md"
      - "C-- 前端中的 Autograd": "1.7/49.md"
      - "在 C-- 中注册调度运算符": "1.7/50.md"
    - "模型优化":
      - "分析您的 PyTorch 模块": "1.7/52.md"
      - "使用 Ray Tune 的超参数调整": "1.7/53.md"
      - "模型剪裁教程": "1.7/54.md"
      - "LSTM 单词语言模型上的动态量化（beta）": "1.7/55.md"
      - "BERT 上的动态量化（Beta）": "1.7/56.md"
      - "PyTorch 中使用 Eager 模式的静态量化（beta）": "1.7/57.md"
      - "计算机视觉的量化迁移学习教程（beta）": "1.7/58.md"
    - "并行和分布式训练":
      - "PyTorch 分布式概述": "1.7/60.md"
      - "单机模型并行最佳实践": "1.7/61.md"
      - "分布式数据并行入门": "1.7/62.md"
      - "用 PyTorch 编写分布式应用": "1.7/63.md"
      - "分布式 RPC 框架入门": "1.7/64.md"
      - "使用分布式 RPC 框架实现参数服务器": "1.7/65.md"
      - "使用 RPC 的分布式管道并行化": "1.7/66.md"
      - "使用异步执行实现批量 RPC 处理": "1.7/67.md"
      - "将分布式DataParallel与分布式 RPC 框架相结合": "1.7/68.md"
  - "PyTorch 1.4 中文文档 & 教程":
    - "入门":
      - "使用 PyTorch 进行深度学习：60 分钟的闪电战":
        - "介绍": "1.4/4.md"
        - "什么是PyTorch": "1.4/blitz/tensor_tutorial.md"
        - "Autograd：自动求导": "1.4/blitz/autograd_tutorial.md"
        - "神经网络": "1.4/blitz/neural_networks_tutorial.md"
        - "训练分类器": "1.4/blitz/cifar10_tutorial.md"
        - "可选：数据并行": "1.4/blitz/data_parallel_tutorial.md"
      - "编写自定义数据集，数据加载器和转换": "1.4/5.md"
      - "使用 TensorBoard 可视化模型，数据和训练": "1.4/6.md"
    - "图片":
      - "TorchVision 对象检测微调教程": "1.4/8.md"
      - "转移学习的计算机视觉教程": "1.4/9.md"
      - "空间变压器网络教程": "1.4/10.md"
      - "使用 PyTorch 进行神经传递": "1.4/11.md"
      - "对抗示例生成": "1.4/12.md"
      - "DCGAN 教程": "1.4/13.md"
    - "音频":
      - "torchaudio 教程": "1.4/15.md"
    - "文本":
      - "NLP From Scratch: 使用char-RNN对姓氏进行分类": "1.4/17.md"
      - "NLP From Scratch: 生成名称与字符级RNN": "1.4/18.md"
      - "NLP From Scratch: 基于注意力机制的 seq2seq 神经网络翻译": "1.4/19.md"
      - "使用 TorchText 进行文本分类": "1.4/20.md"
      - "使用 TorchText 进行语言翻译": "1.4/21.md"
      - "使用 nn.Transformer 和 TorchText 进行序列到序列建模": "1.4/22.md"
    - "命名为 Tensor(实验性）":
      - "(实验性)PyTorch 中的命名张量简介": "1.4/24.md"
    - "强化学习":
      - "强化学习(DQN)教程": "1.4/26.md"
    - "在生产中部署 PyTorch 模型":
      - "通过带有 Flask 的 REST API 在 Python 中部署 PyTorch": "1.4/28.md"
      - "TorchScript 简介": "1.4/29.md"
      - "在 C --中加载 TorchScript 模型": "1.4/30.md"
      - "(可选）将模型从 PyTorch 导出到 ONNX 并使用 ONNX Runtime 运行": "1.4/31.md"
    - "并行和分布式训练":
      - "单机模型并行最佳实践": "1.4/33.md"
      - "分布式数据并行入门": "1.4/34.md"
      - "用 PyTorch 编写分布式应用程序": "1.4/35.md"
      - "分布式 RPC 框架入门": "1.4/36.md"
      - "(高级）带有 Amazon AWS 的 PyTorch 1.0 分布式训练师": "1.4/37.md"
    - "扩展 PyTorch":
      - "使用自定义 C --运算符扩展 TorchScript": "1.4/39.md"
      - "使用自定义 C --类扩展 TorchScript": "1.4/40.md"
      - "使用 numpy 和 scipy 创建扩展": "1.4/41.md"
      - "自定义 C --和 CUDA 扩展": "1.4/42.md"
    - "模型优化":
      - "LSTM Word 语言模型上的(实验）动态量化": "1.4/44.md"
      - "(实验性）在 PyTorch 中使用 Eager 模式进行静态量化": "1.4/45.md"
      - "(实验性）计算机视觉教程的量化转移学习": "1.4/46.md"
      - "(实验）BERT 上的动态量化": "1.4/47.md"
      - "修剪教程": "1.4/48.md"
    - "PyTorch 用其他语言":
      - "使用 PyTorch C --前端": "1.4/50.md"
    - "PyTorch 基础知识":
      - "通过示例学习 PyTorch": "1.4/52.md"
      - "torch.nn 到底是什么？": "1.4/53.md"
    - "笔记":
      - "自动求导机制": "1.4/56.md"
      - "广播语义": "1.4/57.md"
      - "CPU 线程和 TorchScript 推断": "1.4/58.md"
      - "CUDA 语义": "1.4/59.md"
      - "分布式 Autograd 设计": "1.4/60.md"
      - "扩展 PyTorch": "1.4/61.md"
      - "经常问的问题": "1.4/62.md"
      - "大规模部署的功能": "1.4/63.md"
      - "并行处理最佳实践": "1.4/64.md"
      - "重现性": "1.4/65.md"
      - "远程参考协议": "1.4/66.md"
      - "序列化语义": "1.4/67.md"
      - "Windows 常见问题": "1.4/68.md"
      - "XLA 设备上的 PyTorch": "1.4/69.md"
    - "语言绑定":
      - "PyTorch C -- API": "1.4/71.md"
      - "PyTorch Java API": "1.4/72.md"
    - "Python API":
      - "torch": "1.4/74.md"
      - "torch.nn": "1.4/75.md"
      - "torch功能": "1.4/76.md"
      - "torch张量": "1.4/77.md"
      - "张量属性": "1.4/78.md"
      - "自动差分包-Torch.Autograd": "1.4/79.md"
      - "torch.cuda": "1.4/80.md"
      - "分布式通讯包-Torch.Distributed": "1.4/81.md"
      - "概率分布-torch分布": "1.4/82.md"
      - "torch.hub": "1.4/83.md"
      - "torch脚本": "1.4/84.md"
      - "torch.nn.init": "1.4/85.md"
      - "torch.onnx": "1.4/86.md"
      - "torch.optim": "1.4/87.md"
      - "量化": "1.4/88.md"
      - "分布式 RPC 框架": "1.4/89.md"
      - "torch随机": "1.4/90.md"
      - "torch稀疏": "1.4/91.md"
      - "torch存储": "1.4/92.md"
      - "torch.utils.bottleneck": "1.4/93.md"
      - "torch.utils.checkpoint": "1.4/94.md"
      - "torch.utils.cpp_extension": "1.4/95.md"
      - "torch.utils.data": "1.4/96.md"
      - "torch.utils.dlpack": "1.4/97.md"
      - "torch.utils.model_zoo": "1.4/98.md"
      - "torch.utils.tensorboard": "1.4/99.md"
      - "类型信息": "1.4/100.md"
      - "命名张量": "1.4/101.md"
      - "命名为 Tensors 操作员范围": "1.4/102.md"
      - "糟糕！": "1.4/103.md"
    - "torchvision参考":
      - "torchvision": "1.4/105.md"
    - "音频参考":
      - "torchaudio": "1.4/107.md"
    - "torchtext参考":
      - "torchtext": "1.4/109.md"
    - "社区":
      - "PyTorch 贡献指南": "1.4/111.md"
      - "PyTorch 治理": "1.4/112.md"
      - "PyTorch 治理| 感兴趣的人": "1.4/113.md"
  - "PyTorch 1.0 中文文档 & 教程": 
    - "目录": "1.0/README.md"
    - "中文教程":
      - "入门":
        - "PyTorch 深度学习: 60 分钟极速入门":
          - "介绍": "1.0/deep_learning_60min_blitz.md"
          - "什么是 PyTorch？": "1.0/blitz_tensor_tutorial.md"
          - "Autograd：自动求导": "1.0/blitz_autograd_tutorial.md"
          - "神经网络": "1.0/blitz_neural_networks_tutorial.md"
          - "训练分类器": "1.0/blitz_cifar10_tutorial.md"
          - "可选：数据并行处理": "1.0/blitz_data_parallel_tutorial.md"
        - "数据加载和处理教程": "1.0/data_loading_tutorial.md"
        - "用例子学习 PyTorch": "1.0/pytorch_with_examples.md"
        - "迁移学习教程": "1.0/transfer_learning_tutorial.md"
        - "混合前端的 seq2seq 模型部署": "1.0/deploy_seq2seq_hybrid_frontend_tutorial.md"
        - "Saving and Loading Models": "1.0/saving_loading_models.md"
        - "What is torch.nn really?": "1.0/nn_tutorial.md"
      - "图像":
        - "Torchvision 模型微调": "1.0/finetuning_torchvision_models_tutorial.md"
        - "空间变换器网络教程": "1.0/spatial_transformer_tutorial.md"
        - "使用 PyTorch 进行图像风格转换": "1.0/neural_style_tutorial.md"
        - "对抗性示例生成": "1.0/fgsm_tutorial.md"
        - "使用 ONNX 将模型从 PyTorch 传输到 Caffe2 和移动端": "1.0/super_resolution_with_caffe2.md"
      - "文本":
        - "聊天机器人教程": "1.0/chatbot_tutorial.md"
        - "使用字符级别特征的 RNN 网络生成姓氏": "1.0/char_rnn_generation_tutorial.md"
        - "使用字符级别特征的 RNN 网络进行姓氏分类": "1.0/char_rnn_classification_tutorial.md"
        - "Deep Learning for NLP with Pytorch": 
          - "在深度学习和 NLP 中使用 Pytorch": "1.0/deep_learning_nlp_tutorial.md"
          - "PyTorch 介绍": "1.0/nlp_pytorch_tutorial.md"
          - "使用 PyTorch 进行深度学习": "1.0/nlp_deep_learning_tutorial.md"
          - "Word Embeddings: Encoding Lexical Semantics": "1.0/nlp_word_embeddings_tutorial.md"
          - "序列模型和 LSTM 网络": "1.0/nlp_sequence_models_tutorial.md"
          - "Advanced: Making Dynamic Decisions and the Bi-LSTM CRF": "1.0/nlp_advanced_tutorial.md"
        - "基于注意力机制的 seq2seq 神经网络翻译": "1.0/seq2seq_translation_tutorial.md"
      - "生成":
        - "DCGAN Tutorial": "1.0/dcgan_faces_tutorial.md"
      - "强化学习":
        - "Reinforcement Learning (DQN) Tutorial": "1.0/reinforcement_q_learning.md"
      - "扩展 PyTorch":
        - "用 numpy 和 scipy 创建扩展": "1.0/numpy_extensions_tutorial.md"
        - "Custom C-- and CUDA Extensions": "1.0/cpp_extension.md"
        - "Extending TorchScript with Custom C-- Operators": "1.0/torch_script_custom_ops.md"
      - "生产性使用":
        - "Writing Distributed Applications with PyTorch": "1.0/dist_tuto.md"
        - "使用 Amazon AWS 进行分布式训练": "1.0/aws_distributed_training_tutorial.md"
        - "ONNX 现场演示教程": "1.0/ONNXLive.md"
        - "在 C-- 中加载 PYTORCH 模型": "1.0/cpp_export.md"
      - "其它语言中的 PyTorch":
        - "使用 PyTorch C-- 前端": "1.0/cpp_frontend.md"
    - "中文文档":
      - "注解":
        - "自动求导机制": "1.0/notes_autograd.md"
        - "广播语义": "1.0/notes_broadcasting.md"
        - "CUDA 语义": "1.0/notes_cuda.md"
        - "Extending PyTorch": "1.0/notes_extending.md"
        - "Frequently Asked Questions": "1.0/notes_faq.md"
        - "Multiprocessing best practices": "1.0/notes_multiprocessing.md"
        - "Reproducibility": "1.0/notes_randomness.md"
        - "Serialization semantics": "1.0/notes_serialization.md"
        - "Windows FAQ": "1.0/notes_windows.md"
      - "包参考":
        - "torch": 
          - "介绍": "1.0/torch.md"
          - "Tensors": "1.0/torch_tensors.md"
          - "Random sampling": "1.0/torch_random_sampling.md"
          - "Serialization, Parallelism, Utilities": "1.0/torch_serialization_parallelism_utilities.md"
          - "Math operations":
            - "Pointwise Ops": "1.0/torch_math_operations_pointwise_ops.md"
            - "Reduction Ops": "1.0/torch_math_operations_reduction_ops.md"
            - "Comparison Ops": "1.0/torch_math_operations_comparison_ops.md"
            - "Spectral Ops": "1.0/torch_math_operations_spectral_ops.md"
            - "Other Operations": "1.0/torch_math_operations_other_ops.md"
            - "BLAS and LAPACK Operations": "1.0/torch_math_operations_blas_lapack_ops.md"
        - "torch.Tensor": "1.0/tensors.md"
        - "Tensor Attributes": "1.0/tensor_attributes.md"
        - "数据类型信息": "1.0/type_info.md"
        - "torch.sparse": "1.0/sparse.md"
        - "torch.cuda": "1.0/cuda.md"
        - "torch.Storage": "1.0/storage.md"
        - "torch.nn": "1.0/nn.md"
        - "torch.nn.functional": "1.0/nn_functional.md"
        - "torch.nn.init": "1.0/nn_init.md"
        - "torch.optim": "1.0/optim.md"
        - "Automatic differentiation package - torch.autograd": "1.0/autograd.md"
        - "Distributed communication package - torch.distributed": "1.0/distributed.md"
        - "Probability distributions - torch.distributions": "1.0/distributions.md"
        - "Torch Script": "1.0/jit.md"
        - "多进程包 - torch.multiprocessing": "1.0/multiprocessing.md"
        - "torch.utils.bottleneck": "1.0/bottleneck.md"
        - "torch.utils.checkpoint": "1.0/checkpoint.md"
        - "torch.utils.cpp_extension": "1.0/docs_cpp_extension.md"
        - "torch.utils.data": "1.0/data.md"
        - "torch.utils.dlpack": "1.0/dlpack.md"
        - "torch.hub": "1.0/hub.md"
        - "torch.utils.model_zoo": "1.0/model_zoo.md"
        - "torch.onnx": "1.0/onnx.md"
        - "Distributed communication package (deprecated) - torch.distributed.deprecated": "1.0/distributed_deprecated.md"
      - "torchvision 参考": 
        - "目录": "1.0/docs_torchvision_ref.md"
        - "torchvision.datasets": "1.0/torchvision_datasets.md"
        - "torchvision.models": "1.0/torchvision_models.md"
        - "torchvision.transforms": "1.0/torchvision_transforms.md"
        - "torchvision.utils": "1.0/torchvision_utils.md"
  - "PyTorch 0.4 中文文档": "https://pytorch0x.apachecn.org"
  - "PyTorch 0.3 中文文档 & 教程": "https://pytorch0x.apachecn.org"
  - "PyTorch 0.2 中文文档": "https://pytorch0x.apachecn.org"
  - "贡献者": "contrib.md"
  - "关于我们": "https://www.apachecn.org/about/"
  - "中文资源合集": "https://docs.apachecn.org"
